/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "tertiary-fixed": "#c4e7ff",
        "secondary-fixed": "#a8f0e3",
        "on-secondary-fixed-variant": "#005047",
        "inverse-on-surface": "#eff1f4",
        "surface-container-highest": "#e0e3e6",
        "tertiary-container": "#48c4ff",
        "surface": "#f7f9fc",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005322",
        "primary-fixed-dim": "#3de273",
        "tertiary-fixed-dim": "#7cd0ff",
        "on-secondary-container": "#226e63",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004c69",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#00201c",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fc",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "on-primary-container": "#005523",
        "surface-bright": "#f7f9fc",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "on-secondary": "#ffffff",
        "primary": "#006d2f",
        "on-tertiary-fixed": "#001e2c",
        "outline-variant": "#bbcbb9",
        "secondary-fixed-dim": "#8cd4c7",
        "surface-container-high": "#e6e8eb",
        "tertiary": "#00668a",
        "on-primary-fixed": "#002109",
        "on-tertiary-container": "#004f6c",
        "on-error": "#ffffff",
        "secondary": "#1c695f",
        "surface-dim": "#d8dadd",
        "outline": "#6c7b6b",
        "primary-container": "#25d366",
        "inverse-primary": "#3de273",
        "surface-tint": "#006d2f",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3c4a3d",
        "primary-fixed": "#66ff8e",
        "on-background": "#191c1e",
        "secondary-container": "#a5ede0",
        "on-surface": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "12px",
        "container-padding": "16px",
        "stack-lg": "24px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "label-sm": ["JetBrains Mono"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
